project_id = "ovscskaijvclaxelkdyf"

[functions.elevenlabs-transcribe]
verify_jwt = false

[functions.analyze-gulf-arabic]
verify_jwt = false

[functions.download-media]
verify_jwt = false

[functions.munsit-transcribe]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.falcon-translate]
verify_jwt = false

[functions.classify-tutor-segments]
verify_jwt = false

[functions.analyze-meme]
verify_jwt = false

[functions.generate-flashcard-image]
verify_jwt = false

[functions.falcon-warmup]
verify_jwt = false
